#!/bin/bash

# Update Ubuntu and get standard repository programs
./scripts/aptinstall.sh

# Run all programs/ install scripts
for f in scripts/programs/*.sh; do bash "$f" -H; done

# Get all upgrades
sudo apt upgrade -y

# See our zsh changes
source ~/.zshrc
